# Site settings
title: moaxcp.github.io
email: moaxcp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  java, gentoo, and programming topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://moaxcp.github.com" # the base hostname & protocol for your site
github_username:  moaxcp

# Build settings
markdown: kramdown
